boot.o: boot.S multiboot.h x86_desc.h types.h
paging_call.o: paging_call.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h paging.h filesys.h devices/rtc.h devices/../lib.h \
  devices/../i8259.h devices/keyboard.h devices/terminal.h \
  devices/../types.h
lib.o: lib.c lib.h types.h devices/keyboard.h devices/../lib.h \
  devices/../i8259.h devices/../types.h devices/terminal.h \
  devices/../types.h
paging.o: paging.c paging.h types.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h paging.h \
  interrupt_handlers/syscall.h interrupt_handlers/exception.h \
  interrupt_handlers/idt.h filesys.h devices/rtc.h devices/../lib.h \
  devices/../i8259.h devices/../types.h devices/keyboard.h \
  devices/terminal.h devices/../types.h
device_handlers.o: interrupt_handlers/device_handlers.S
exceptions_def.o: interrupt_handlers/exceptions_def.S
syscall.o: interrupt_handlers/syscall.S
keyboard.o: devices/keyboard.c devices/keyboard.h devices/../lib.h \
  devices/../types.h devices/../i8259.h devices/keyboard_scancodes.h \
  devices/terminal.h devices/../types.h
rtc.o: devices/rtc.c devices/rtc.h devices/../lib.h devices/../types.h \
  devices/../i8259.h
terminal.o: devices/terminal.c devices/terminal.h devices/../lib.h \
  devices/../types.h devices/../types.h devices/keyboard.h \
  devices/../i8259.h
exception.o: interrupt_handlers/exception.c \
  interrupt_handlers/exception.h interrupt_handlers/../lib.h \
  interrupt_handlers/../types.h interrupt_handlers/syscalls_def.h \
  interrupt_handlers/../types.h
idt.o: interrupt_handlers/idt.c interrupt_handlers/idt.h \
  interrupt_handlers/../x86_desc.h interrupt_handlers/../types.h \
  interrupt_handlers/exceptions_def.h interrupt_handlers/exception.h \
  interrupt_handlers/syscall.h interrupt_handlers/device_handlers.h \
  interrupt_handlers/../devices/rtc.h \
  interrupt_handlers/../devices/../lib.h \
  interrupt_handlers/../devices/../types.h \
  interrupt_handlers/../devices/../i8259.h \
  interrupt_handlers/../devices/keyboard.h
syscalls_def.o: interrupt_handlers/syscalls_def.c \
  interrupt_handlers/syscalls_def.h interrupt_handlers/../types.h \
  interrupt_handlers/../lib.h interrupt_handlers/../types.h
